# 백준 5339번 문제
print("     /~\ ")
print("    ( oo|")
print("    _\=/_")
print("   /  _  \ ")
print("  //|/.\|\\\ ")
print(" ||  \ /  ||")
print("============")
print("|          |")
print("|          |")
print("|          |")